Repository amberframework/granite, pull requests merged in 2018-06, with the labels that each got.

#220 Fix last insert ID race condition
  spec/granite/transactions/create_spec.cr
  src/adapter/mysql.cr
  src/adapter/pg.cr
  src/granite/transactions.cr
Labels: kind:bug, pr:needs-review

#215 added query macro, tests, and docs
  README.md
  spec/granite/select/select_spec.cr
  spec/spec_models.cr
  src/adapter/base.cr
  src/adapter/mysql.cr
  src/adapter/pg.cr
  src/adapter/sqlite.cr
  src/granite/base.cr
  src/granite/querying.cr
  src/granite/select.cr
Labels: kind:breaking-change, kind:enhancement, kind:feature, pr:wip

#221 Support model.from_json(JSON::Any)
  README.md
  spec/granite/transactions/create_spec.cr
  spec/granite_spec.cr
  src/granite/error.cr
  src/granite/fields.cr
  src/granite/transactions.cr
Labels: kind:enhancement

#224 bugfix: querybuilder logger
  src/granite/query/executors/base.cr
Labels: kind:bug, kind:enhancement, pr:needs-review

#227 Added uniqueness validator for models
  README.md
  spec/granite/validations/validation_helpers_spec.cr
  src/granite/validation_helpers.cr
Labels: kind:enhancement, pr:needs-review

#228 Update to crystal 0.25.0
  Dockerfile
  shard.yml
  spec/granite/fields/timestamps_spec.cr
  spec/granite/querying/find_by_spec.cr
  spec/granite/querying/from_sql_spec.cr
  spec/granite_spec.cr
  src/granite.cr
  src/granite/base.cr
  src/granite/fields.cr
  src/granite/querying.cr
  src/granite/transactions.cr
Labels: kind:breaking-change, pr:needs-review, pr:wip

#231 Further update Granite to be compatible with Crystal 0.25
  shard.yml
  spec/granite/fields/timestamps_spec.cr
  spec/granite/querying/from_sql_spec.cr
  spec/granite/transactions/import_spec.cr
  src/adapter/mysql.cr
  src/adapter/pg.cr
  src/adapter/sqlite.cr
  src/granite/base.cr
  src/granite/fields.cr
  src/granite/querying.cr
  src/granite/transactions.cr
Labels: kind:breaking-change, pr:needs-review

#232 Adding transaction raise methods
  README.md
  spec/granite/exceptions/record_invalid_spec.cr
  spec/granite/exceptions/record_not_destroyed_spec.cr
  spec/granite/transactions/create_spec.cr
  spec/granite/transactions/destroy_spec.cr
  spec/granite/transactions/save_spec.cr
  spec/granite/transactions/update_spec.cr
  spec/spec_models.cr
  src/granite/exceptions.cr
  src/granite/transactions.cr
Labels: kind:feature

#240 Add ameba
  .dockerignore
  .gitignore
  docker-compose.yml
  shard.yml
  spec/granite/query/spec_helper.cr
  spec/granite/validations/validation_helpers_spec.cr
  spec/granite_spec.cr
  spec/mocks/db_mock.cr
  src/adapter/mysql.cr
  src/adapter/pg.cr
  src/adapter/sqlite.cr
  src/granite.cr
  src/granite/query/assemblers/postgresql.cr
  src/granite/table.cr
  src/granite/validation_helpers.cr
Labels: kind:enhancement, pr:needs-review

#241 Update database docker
  docker-compose.yml
Labels: kind:dependency, pr:needs-review
