Repository amberframework/granite, pull requests merged in 2018-05, with the labels that each got.

#192 Use most recent version in granite docker image
  Dockerfile
Labels: kind:enhancement, pr:needs-review

#186 Support belongs_to custom method name
  spec/granite_orm/associations/belongs_to_custom_type_spec.cr
  spec/granite_orm/associations/belongs_to_spec.cr
  spec/spec_models.cr
  src/granite_orm/associations.cr
Labels: kind:enhancement, pr:needs-review

#194 UUID Spec + Usage
  README.md
  spec/granite_orm/associations/has_many_spec.cr
  spec/granite_orm/associations/has_many_through_spec.cr
  spec/granite_orm/fields/uuid_spec.cr
  spec/granite_orm/query/assembler/postgresql_spec.cr
  spec/granite_orm/query/builder_spec.cr
  spec/granite_orm/querying/from_sql_spec.cr
  spec/mocks/db_mock.cr
  spec/spec_models.cr
  src/granite_orm/association_collection.cr
  src/granite_orm/collection.cr
  src/granite_orm/query/assemblers/postgresql.cr
  src/granite_orm/query/builder.cr
  src/granite_orm/querying.cr
Labels: kind:enhancement

#195 Manually trigger callbacks
  spec/granite_orm/callbacks/callbacks_spec.cr
  src/granite_orm/callbacks.cr
Labels: kind:enhancement

#191 Bulk import batch size
  README.md
  spec/granite_orm/transactions/import_spec.cr
  src/granite_orm/transactions.cr
Labels: kind:enhancement, pr:needs-review

#196 Update README for manually running callbacks
  README.md
Labels: kind:documentation, pr:needs-review

#201 Fixes to Migrator provided by Maiha
  README.md
  spec/spec_models.cr
  src/adapter/base.cr
  src/adapter/mysql.cr
  src/adapter/pg.cr
  src/adapter/sqlite.cr
  src/granite_orm/base.cr
  src/granite_orm/migrator.cr
Labels: kind:enhancement, pr:needs-review

#187 Refactor transactions
  src/granite_orm/transactions.cr
Labels: pr:needs-review

#202 remove extra abstraction and _run_
  src/granite_orm/callbacks.cr
  src/granite_orm/transactions.cr
Labels: kind:enhancement, pr:needs-review

#205 Update amber repository link
  README.md
Labels: kind:enhancement, pr:needs-review

#219 Validation Helpers
  README.md
  spec/granite/validations/validation_helpers_spec.cr
  src/granite/base.cr
  src/granite/validation_helpers.cr
Labels: kind:documentation, pr:needs-review

#211 Allow `find_by` to accept multiple arguments
  README.md
  spec/granite/associations/has_many_spec.cr
  spec/granite/associations/has_many_through_spec.cr
  spec/granite/fields/timestamps_spec.cr
  spec/granite/querying/find_by_spec.cr
  spec/granite/querying/find_spec.cr
  spec/granite/querying/first_spec.cr
  src/adapter/base.cr
  src/adapter/mysql.cr
  src/adapter/pg.cr
  src/adapter/sqlite.cr
  src/granite/association_collection.cr
  src/granite/querying.cr
Labels: kind:breaking-change, pr:needs-review
