Repository amberframework/granite, pull requests merged in 2018-04, with the labels that each got.

#173 Update links and code samples
  README.md
Labels: pr:needs-review

#181 Add field! for property!
  spec/granite_orm/fields/field_spec.cr
  src/granite_orm/fields.cr
  src/granite_orm/querying.cr
  src/granite_orm/table.cr
Labels: kind:enhancement, pr:needs-review

#176 Change .all and has_many to return *Collection object
  spec/granite_orm/associations/has_many_spec.cr
  spec/granite_orm/associations/has_many_through_spec.cr
  src/granite_orm/association_collection.cr
  src/granite_orm/associations.cr
  src/granite_orm/base.cr
  src/granite_orm/collection.cr
  src/granite_orm/querying.cr
Labels: kind:breaking-change, pr:needs-review

#183 Some enhancements about callbacks
  spec/granite_orm/callbacks/abort_spec.cr
  spec/spec_models.cr
  src/granite_orm/callbacks.cr
  src/granite_orm/transactions.cr
Labels: kind:enhancement

#132 Minimally useful query syntax
  spec/granite_orm/query/assembler/postgresql_spec.cr
  spec/granite_orm/query/builder_spec.cr
  spec/granite_orm/query/executor_spec.cr
  spec/granite_orm/query/spec_helper.cr
  src/granite_orm.cr
  src/granite_orm/query/assemblers/base.cr
  src/granite_orm/query/assemblers/postgresql.cr
  src/granite_orm/query/builder.cr
  src/granite_orm/query/builder_methods.cr
  src/granite_orm/query/executor.cr
  src/granite_orm/query/executors/base.cr
  src/granite_orm/query/executors/list.cr
  src/granite_orm/query/executors/one.cr
  src/granite_orm/query/executors/value.cr
  src/query_builder.cr
Labels: kind:enhancement
