Repository amberframework/granite, pull requests merged in 2018-10, with the labels that each got.

#288 crystal 0.26.1 support
  Dockerfile
  src/granite/base.cr
Labels: kind:bug, pr:needs-review

#286 Support PG Array types
  spec/granite_spec.cr
  spec/spec_models.cr
  src/adapter/pg.cr
  src/granite/fields.cr
Labels: kind:enhancement, pr:needs-review

#289 Annotation support
  README.md
  docs/getting_started.md
  spec/run_all_specs.sh
  src/granite/base.cr
  src/granite/fields.cr
  src/granite/table.cr
Labels: kind:enhancement, pr:needs-review

#290 Dj/include query builder
  spec/granite/query/spec_helper.cr
  src/granite.cr
  src/granite/base.cr
  src/granite/query/builder.cr
  src/granite/query/builder_methods.cr
  src/granite/querying.cr
  src/granite/transactions.cr
  src/query_builder.cr
Labels: pr:needs-review

#293 Better UUID support
  docs/getting_started.md
  spec/granite/fields/uuid_spec.cr
  spec/spec_models.cr
  src/adapter/mysql.cr
  src/adapter/pg.cr
  src/adapter/sqlite.cr
  src/granite/fields.cr
  src/granite/migrator.cr
  src/granite/table.cr
  src/granite/transactions.cr
Labels: kind:enhancement, pr:needs-review

#297 Add support for AND and OR clause
  spec/granite/query/builder_spec.cr
  src/granite/query/assemblers/base.cr
  src/granite/query/builder.cr
Labels: pr:needs-review

#301 Only define `updated/created_at` properties if they are wanted
  spec/granite_spec.cr
  spec/spec_models.cr
  src/granite/transactions.cr
Labels: kind:enhancement, pr:needs-review

#303 Use env vars to specify sqlite version
  .env
  .travis.yml
  Dockerfile
  docker/docker-compose.sqlite.yml
Labels: kind:enhancement, pr:needs-review

#304 Belongs_to refactor
  docker-compose.yml
  spec/granite/associations/belongs_to_spec.cr
  spec/spec_models.cr
  src/granite/associations.cr
Labels: kind:enhancement
