Repository amberframework/granite, pull requests merged in 2018-07, with the labels that each got.

#247 fix conflicting use of query
  README.md
  spec/granite/querying/passthrough_spec.cr
  spec/spec_models.cr
  src/granite/select.cr
Labels: kind:breaking-change, pr:needs-review

#253 Support JSON::Serializable
  Dockerfile
  README.md
  spec/granite/transactions/create_spec.cr
  spec/granite_spec.cr
  spec/spec_models.cr
  src/granite/base.cr
  src/granite/callbacks.cr
  src/granite/fields.cr
  src/granite/transactions.cr
  src/granite/validators.cr
Labels: kind:breaking-change, kind:enhancement, pr:needs-review

#256 Split docs into smaller files
  README.md
  docs/Granite.html
  docs/Granite/Adapter.html
  docs/Granite/Adapter/Base.html
  docs/Granite/Adapter/Base/Schema.html
  docs/Granite/Adapter/Mysql.html
  docs/Granite/Adapter/Mysql/Schema.html
  docs/Granite/Adapter/Pg.html
  docs/Granite/Adapter/Pg/Schema.html
  docs/Granite/Adapter/Sqlite.html
  docs/Granite/Adapter/Sqlite/Schema.html
  docs/Granite/AssociationCollection.html
  docs/Granite/Associations.html
  docs/Granite/Base.html
  docs/Granite/Callbacks.html
  docs/Granite/Callbacks/Abort.html
  docs/Granite/Collection.html
  docs/Granite/Error.html
  docs/Granite/Fields.html
  docs/Granite/Fields/Type.html
  docs/Granite/Migrator.html
  docs/Granite/Migrator/Base.html
  docs/Granite/Query.html
  docs/Granite/Query/Assembler.html
  docs/Granite/Query/Assembler/Base.html
  docs/Granite/Query/Assembler/Postgresql.html
  docs/Granite/Query/Builder.html
  docs/Granite/Query/Builder/FieldData.html
  docs/Granite/Query/Builder/FieldName.html
  docs/Granite/Query/Builder/Sort.html
  docs/Granite/Query/BuilderMethods.html
  docs/Granite/Query/Executor.html
  docs/Granite/Query/Executor/List.html
  docs/Granite/Query/Executor/Shared.html
  docs/Granite/Query/Executor/Value.html
  docs/Granite/Querying.html
  docs/Granite/Querying/NotFound.html
  docs/Granite/Settings.html
  docs/Granite/Table.html
  docs/Granite/Transactions.html
  docs/Granite/Transactions/ClassMethods.html
  docs/Granite/Validators.html
  docs/callbacks.md
  docs/crud.md
  docs/css/style.css
  docs/getting_started.md
  docs/imports.md
  docs/index.html
  docs/index.json
  docs/js/doc.js
  docs/json_support.md
  docs/migrations.md
  docs/querying.md
  docs/relationships.md
  docs/validations.md
  docs/yaml_support.md
  shard.yml
Labels: kind:documentation, pr:needs-review

#255 Support YAML::Serializable
  spec/granite_spec.cr
  spec/spec_models.cr
  src/granite/base.cr
  src/granite/callbacks.cr
  src/granite/fields.cr
  src/granite/transactions.cr
  src/granite/validators.cr
Labels: kind:feature, pr:needs-review

#261 Optionally add nodoc
  docs/getting_started.md
  src/granite/callbacks.cr
  src/granite/fields.cr
  src/granite/migrator.cr
  src/granite/querying.cr
  src/granite/table.cr
  src/granite/transactions.cr
  src/granite/validators.cr
Labels: kind:documentation, kind:enhancement, pr:needs-review

#262 Revert `.is_a?(JSON::Any)`
  src/granite/fields.cr
Labels: kind:enhancement, pr:needs-review
